import { Member, Project, Task, ChatChannel, ChatMessage, NotificationItem, Role } from './types';

export const INITIAL_ROLES: Role[] = [
  {
    id: 'role_admin',
    name: '系统管理员',
    description: '拥有所有权限，可管理成员、角色、项目和任务',
    color: 'bg-emerald-600',
    permissions: ['assign_task', 'create_task', 'delete_task', 'manage_members', 'manage_roles', 'manage_projects'],
  },
  {
    id: 'role_pm',
    name: '产品经理 (PM)',
    description: '负责需求管理与任务分配，可创建和指派任务',
    color: 'bg-blue-600',
    permissions: ['assign_task', 'create_task', 'delete_task'],
  },
  {
    id: 'role_dev',
    name: '开发工程师',
    description: '负责开发实现，可创建任务但不能指派',
    color: 'bg-indigo-600',
    permissions: ['create_task'],
  },
  {
    id: 'role_designer',
    name: '设计师',
    description: '负责 UI/UX 设计，可创建任务但不能指派',
    color: 'bg-rose-600',
    permissions: ['create_task'],
  },
  {
    id: 'role_devops',
    name: 'DevOps 工程师',
    description: '负责部署运维，可创建任务但不能指派',
    color: 'bg-amber-600',
    permissions: ['create_task'],
  },
  {
    id: 'role_ai',
    name: '智能助手',
    description: 'AI 协作助手，辅助任务总结与分析',
    color: 'bg-purple-600',
    permissions: [],
  },
];

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'usr_alex',
    name: '陈亚历 (Alex)',
    role: 'Tech Lead / 架构师',
    roleId: 'role_admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
    avatarBg: 'bg-emerald-600',
    email: 'alex.chen@tasksync.io',
    status: 'online',
    statusText: '正在评审底层数据结构与未来架构迭代规划',
    workloadCount: 3,
    isAdmin: true,
  },
  {
    id: 'usr_sarah',
    name: '张婷婷 (Sarah)',
    role: '前端资深工程师',
    roleId: 'role_dev',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
    avatarBg: 'bg-indigo-600',
    email: 'sarah.zhang@tasksync.io',
    status: 'online',
    statusText: '正在设计可视化工时热力图与甘特图交互',
    workloadCount: 2,
  },
  {
    id: 'usr_david',
    name: '李明 (David)',
    role: '后端核心架构师',
    roleId: 'role_dev',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    avatarBg: 'bg-blue-600',
    email: 'david.li@tasksync.io',
    status: 'busy',
    statusText: '研发禅道 Webhook 增量双向同步模块',
    workloadCount: 2,
  },
  {
    id: 'usr_emma',
    name: '赵艾玛 (Emma)',
    role: 'UI/UX 体验专家',
    roleId: 'role_designer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=150',
    avatarBg: 'bg-rose-600',
    email: 'emma.zhao@tasksync.io',
    status: 'away',
    statusText: '准备全渠道机器人通知卡片 UI 设计规范',
    workloadCount: 1,
  },
  {
    id: 'usr_ai',
    name: '牛磨 Copilot (AI)',
    role: '智能协作助手',
    roleId: 'role_ai',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=150',
    avatarBg: 'bg-purple-600',
    email: 'copilot@tasksync.io',
    status: 'online',
    statusText: '正在实时预测 Sprint 进度风险',
    workloadCount: 1,
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj_cloud',
    name: '牛磨 Cloud v2.4 敏捷迭代',
    key: 'TS-CLOUD',
    description: '核心协同平台升级，重点优化多人实时沟通、看板交互、禅道增量同步与 AI 风险预测。',
    color: 'emerald',
    memberIds: ['usr_alex', 'usr_sarah', 'usr_david', 'usr_emma', 'usr_ai'],
    template: 'scrum',
  }
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_opt_1',
    title: '【1. 新建项目阶段】项目模板预设与阶段里程碑 (Milestones) 规划向导',
    description: '<p><strong>业务痛点分析：</strong>目前创建项目时仅填写名称与描述，缺乏结构化框架约束，导致新项目进入后缺乏明确的阶段目标。</p><p><strong>优化方案：</strong>在【新建项目 Modal】中引入敏捷 Scrum、 Kanban 看板、Bug 缺陷管理等预置模版。创建时同步初始化 Milestone 里程碑（如 MVP 发布、 Alpha 交付、 Beta 封板），自动带出对应阶段的默认任务集与标准工作流。</p>',
    status: 'in_progress',
    priority: 'high',
    assigneeIds: ['usr_alex', 'usr_emma'],
    reporterId: 'usr_alex',
    projectId: 'proj_cloud',
    startDate: '2026-08-08',
    dueDate: '2026-08-16',
    estimatedHours: 20,
    loggedHours: 0,
    tags: ['项目新建', '里程碑', '模版向导', '流程优化'],
    color: 'emerald',
    checklist: [
      { id: 'chk_o1_1', title: '新增 ProjectTemplate 预设结构 (Scrum 敏捷 / 研发缺陷 / 运营看板)', completed: false, assigneeId: 'usr_alex' },
      { id: 'chk_o1_2', title: '在 CreateProjectModal 中增加步骤条向导与里程碑初始设定', completed: false, assigneeId: 'usr_emma' },
      { id: 'chk_o1_3', title: '项目大盘与甘特图支持按 Milestone 里程碑维度进行层级筛选', completed: false, assigneeId: 'usr_sarah' }
    ],
    comments: [],
    activities: [
      {
        id: 'act_o1_1',
        taskId: 'task_opt_1',
        authorId: 'usr_alex',
        action: '创建任务',
        details: '规划【新建项目阶段】优化任务',
        timestamp: '2026-08-05 18:30',
      }
    ],
    attachmentsCount: 1,
    createdAt: '2026-08-05T18:30:00.000Z',
    updatedAt: '2026-08-05T18:30:00.000Z',
  },
  {
    id: 'task_opt_2',
    title: '【2. 任务分解阶段】父子任务层级树与前置依赖关联 (Task Dependencies)',
    description: '<p><strong>业务痛点分析：</strong>复杂需求平铺展示时难以分辨先后依赖关系，容易发生前置开发未完成而后续任务盲目开工的情况。</p><p><strong>优化方案：</strong>支持任务卡片间建立 Blocked by (被阻塞) / Blocks (阻塞) 双向依赖映射。当存在未完成的前置依赖时，看板与卡片上高亮显示“前置阻断”警示，并在甘特图呈现依赖连线。</p>',
    status: 'todo',
    priority: 'urgent',
    assigneeIds: ['usr_sarah', 'usr_david'],
    reporterId: 'usr_alex',
    projectId: 'proj_cloud',
    startDate: '2026-08-10',
    dueDate: '2026-08-20',
    estimatedHours: 28,
    loggedHours: 0,
    tags: ['任务分解', '前置依赖', '甘特图联动', '阻断预警'],
    color: 'rose',
    checklist: [
      { id: 'chk_o2_1', title: '扩展 Task 数据模型，新增 dependsOnTaskIds 属性', completed: false, assigneeId: 'usr_david' },
      { id: 'chk_o2_2', title: '任务详情 Modal 增加“依赖关系”管理面板与关联搜索选择器', completed: false, assigneeId: 'usr_sarah' },
      { id: 'chk_o2_3', title: '看板卡片与甘特图中绘制依赖警示标记与阻断图标', completed: false, assigneeId: 'usr_sarah' }
    ],
    comments: [],
    activities: [],
    attachmentsCount: 0,
    createdAt: '2026-08-05T18:32:00.000Z',
    updatedAt: '2026-08-05T18:32:00.000Z',
  },
  {
    id: 'task_opt_3',
    title: '【3. 质量门禁阶段】工作流状态机约束与测试用例 (Test Cases) 联动',
    description: '<p><strong>业务痛点分析：</strong>当前任务状态流转缺乏角色校验与质量防呆，研发人员可直接将未经测试的任务推至 Done。</p><p><strong>优化方案：</strong>建立按角色约束的状态机流转规则（如仅具有 QA 角色或测试负责人才能将卡片从 Review 改为 Done）。同时在 Review 阶段引入“测试用例与测试结果”勾选项，未通过测试前限制关单。</p>',
    status: 'todo',
    priority: 'high',
    assigneeIds: ['usr_david', 'usr_alex'],
    reporterId: 'usr_alex',
    projectId: 'proj_cloud',
    startDate: '2026-08-12',
    dueDate: '2026-08-22',
    estimatedHours: 24,
    loggedHours: 0,
    tags: ['质量门禁', '状态机', '测试用例', '防呆规则'],
    color: 'indigo',
    checklist: [
      { id: 'chk_o3_1', title: '在 permissions.ts 中引入工作流卡口校验函数 canTransitionTaskStatus()', completed: false, assigneeId: 'usr_alex' },
      { id: 'chk_o3_2', title: '任务卡片新增 TestCases 测试用例清单与通过率指标', completed: false, assigneeId: 'usr_david' },
      { id: 'chk_o3_3', title: '看板拖拽触发非法状态变更时弹出阻断提示与质量门禁原因说明', completed: false, assigneeId: 'usr_sarah' }
    ],
    comments: [],
    activities: [],
    attachmentsCount: 0,
    createdAt: '2026-08-05T18:35:00.000Z',
    updatedAt: '2026-08-05T18:35:00.000Z',
  },
  {
    id: 'task_opt_4',
    title: '【4. 执行协同阶段】任务打卡秒表 (Live Timer) 与即时工时日志自动记录',
    description: '<p><strong>业务痛点分析：</strong>成员手动填报 Logged Hours 容易遗忘或预估不准，无法反映真实的工时消耗轨迹。</p><p><strong>优化方案：</strong>在任务详情与看板悬浮中提供一键“开始计时 / 暂停”秒表挂件。工作结束点击停止后，自动计算分钟数并生成对应日期的 Worklog 明细，可同步至团队负荷热力图。</p>',
    status: 'todo',
    priority: 'medium',
    assigneeIds: ['usr_sarah', 'usr_emma'],
    reporterId: 'usr_alex',
    projectId: 'proj_cloud',
    startDate: '2026-08-14',
    dueDate: '2026-08-24',
    estimatedHours: 18,
    loggedHours: 0,
    tags: ['工时计时', '打卡秒表', '沉浸协同', '过程追溯'],
    color: 'teal',
    checklist: [
      { id: 'chk_o4_1', title: '设计全局 TaskTimerContext，支持在顶部导航栏悬浮运行中的任务计时秒表', completed: false, assigneeId: 'usr_sarah' },
      { id: 'chk_o4_2', title: '计时结束自动弹出工时说明与 Worklog 确认提交对话框', completed: false, assigneeId: 'usr_emma' },
      { id: 'chk_o4_3', title: '任务详情页渲染按日期展开的工时日志流 (Worklog History)', completed: false, assigneeId: 'usr_sarah' }
    ],
    comments: [],
    activities: [],
    attachmentsCount: 0,
    createdAt: '2026-08-05T18:38:00.000Z',
    updatedAt: '2026-08-05T18:38:00.000Z',
  },
  {
    id: 'task_opt_5',
    title: '【5. 验收归档阶段】一键生成迭代版本日志 (Release Notes) 与产出成果包',
    description: '<p><strong>业务痛点分析：</strong>迭代结束后，PM 与研发需要花费大量时间手动整理该版本完成的特性与修复的 Bug。</p><p><strong>优化方案：</strong>在版本封板阶段提供“一键生成 Release Notes”功能。系统结合已进入 Done 状态的任务、关联的 Git Commit 与禅道需求，通过 AI Copilot 总结自动撰写标准 Markdown 交付报告。</p>',
    status: 'todo',
    priority: 'high',
    assigneeIds: ['usr_ai', 'usr_alex'],
    reporterId: 'usr_alex',
    projectId: 'proj_cloud',
    startDate: '2026-08-18',
    dueDate: '2026-08-26',
    estimatedHours: 16,
    loggedHours: 0,
    tags: ['验收归档', 'ReleaseNotes', 'AI文档生成', '迭代交付'],
    color: 'amber',
    checklist: [
      { id: 'chk_o5_1', title: '设计 Copilot 提炼完成任务集生成标准 CHANGELOG.md 的 Prompt', completed: false, assigneeId: 'usr_ai' },
      { id: 'chk_o5_2', title: '开发 ReleaseNotesModal 支持预览、富文本导出与一键发送至全员通知群', completed: false, assigneeId: 'usr_alex' }
    ],
    comments: [],
    activities: [],
    attachmentsCount: 0,
    createdAt: '2026-08-05T18:40:00.000Z',
    updatedAt: '2026-08-05T18:40:00.000Z',
  },
  {
    id: 'task_opt_6',
    title: '【6. 复盘闭环阶段】敏捷迭代复盘画布 (Retrospective) 与改进项流转追踪',
    description: '<p><strong>业务痛点分析：</strong>团队复盘会议记录往往散落在文档中，提出的改进动作 (Action Items) 容易失追，无法形成持续改进闭环。</p><p><strong>优化方案：</strong>新增敏捷复盘 Retrospective 画布模块，包含“做得好的 (Went Well)”、“需改进的 (Improve)”、“行动项 (Action Items)”三列。复盘得出的行动项支持一键转换为下一 Sprint 的待办任务。</p>',
    status: 'todo',
    priority: 'medium',
    assigneeIds: ['usr_alex', 'usr_emma'],
    reporterId: 'usr_alex',
    projectId: 'proj_cloud',
    startDate: '2026-08-20',
    dueDate: '2026-08-28',
    estimatedHours: 22,
    loggedHours: 0,
    tags: ['敏捷复盘', '持续改进', 'ActionItems', '闭环管理'],
    color: 'violet',
    checklist: [
      { id: 'chk_o6_1', title: '开发 Retrospective 互动复盘看板组件与匿名点赞投选机制', completed: false, assigneeId: 'usr_emma' },
      { id: 'chk_o6_2', title: '复盘 Action Item 卡片支持一键按钮转换为下一期 Todo 任务', completed: false, assigneeId: 'usr_alex' }
    ],
    comments: [],
    activities: [],
    attachmentsCount: 0,
    createdAt: '2026-08-05T18:42:00.000Z',
    updatedAt: '2026-08-05T18:42:00.000Z',
  }
];

export const INITIAL_CHANNELS: ChatChannel[] = [
  {
    id: 'chan_sprint',
    projectId: 'proj_cloud',
    name: 'sprint-24-迭代沟通',
    description: 'Sprint 24 每日站会、代码评审及日常开发阻碍讨论频道',
    isPrivate: false,
    unreadCount: 0,
  },
  {
    id: 'chan_design',
    projectId: 'proj_cloud',
    name: 'design-设计交流',
    description: 'UI/UX 规范、交互原型图走查及设计反馈讨论',
    isPrivate: false,
    unreadCount: 0,
  },
  {
    id: 'chan_architecture',
    projectId: 'proj_cloud',
    name: 'architecture-技术架构',
    description: '底层数据协议、API接口规范、性能优化与安全性研讨',
    isPrivate: false,
    unreadCount: 0,
  },
  {
    id: 'chan_general',
    projectId: 'proj_cloud',
    name: 'team-大堂茶水间',
    description: '团队日常公告、灵感分享与休闲交流',
    isPrivate: false,
    unreadCount: 0,
  }
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: 'msg_1',
    channelId: 'chan_sprint',
    authorId: 'usr_alex',
    content: '工作空间已初始化完成，可以开始创建任务或从禅道同步任务了。',
    createdAt: '2026-08-02 09:30',
  },
  {
    id: 'msg_2',
    channelId: 'chan_sprint',
    authorId: 'usr_ai',
    content: '我是牛磨 Copilot，可以帮你拆解任务、生成站会报告，随时呼唤我。',
    createdAt: '2026-08-02 09:35',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];
