import { Member, Project, Task, ChatChannel, ChatMessage, NotificationItem } from './types';

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'usr_alex',
    name: '陈亚历 (Alex)',
    role: 'Tech Lead / 架构师',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
    avatarBg: 'bg-emerald-600',
    email: 'alex.chen@tasksync.io',
    status: 'online',
    statusText: '正在评审底层数据结构与协同协议',
    workloadCount: 4,
  },
  {
    id: 'usr_sarah',
    name: '张莎拉 (Sarah)',
    role: '资深前端工程师',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
    avatarBg: 'bg-indigo-600',
    email: 'sarah.zhang@tasksync.io',
    status: 'online',
    statusText: '重构看板拖拽组件中',
    workloadCount: 5,
  },
  {
    id: 'usr_michael',
    name: '王麦克 (Michael)',
    role: '高级产品经理 (PM)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    avatarBg: 'bg-blue-600',
    email: 'michael.wang@tasksync.io',
    status: 'busy',
    statusText: '开 Sprint 24 需求评审会',
    workloadCount: 3,
  },
  {
    id: 'usr_elena',
    name: '刘艾琳 (Elena)',
    role: 'UI/UX 资深设计师',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=150',
    avatarBg: 'bg-rose-600',
    email: 'elena.liu@tasksync.io',
    status: 'online',
    statusText: '设计暗黑模式与状态图表',
    workloadCount: 2,
  },
  {
    id: 'usr_david',
    name: '金大卫 (David)',
    role: '后端 & DevOps 工程师',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150',
    avatarBg: 'bg-amber-600',
    email: 'david.kim@tasksync.io',
    status: 'away',
    statusText: '部署 CI/CD 流水线中',
    workloadCount: 3,
  },
  {
    id: 'usr_ai',
    name: 'TaskSync Copilot (AI)',
    role: '智能协作助手',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=150',
    avatarBg: 'bg-purple-600',
    email: 'copilot@tasksync.io',
    status: 'online',
    statusText: '随时准备回答或总结任务',
    workloadCount: 0,
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj_cloud',
    name: 'TaskSync Cloud v2.4 敏捷迭代',
    key: 'TS-CLOUD',
    description: '核心协同平台升级，重点优化多人实时沟通、看板交互与自动化工作流。',
    color: 'emerald',
    memberIds: ['usr_alex', 'usr_sarah', 'usr_michael', 'usr_elena', 'usr_david', 'usr_ai'],
  },
  {
    id: 'proj_mobile',
    name: '移动端 App 跨平台重构',
    key: 'TS-MOB',
    description: '针对 iOS 与 Android 的极速实时任务通知与移动协同优化。',
    color: 'indigo',
    memberIds: ['usr_alex', 'usr_sarah', 'usr_elena'],
  },
  {
    id: 'proj_growth',
    name: '增长与客户成功工具链',
    key: 'TS-GROW',
    description: '搭建自动化客户工单联动与数据埋点分析看板。',
    color: 'amber',
    memberIds: ['usr_michael', 'usr_david'],
  }
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'TS-101',
    title: '实现多人实时协作看板的 WebSocket 动态状态同步',
    description: '当任一成员拖拽卡片、修改优先级或分配经办人时，同项目下的所有协同成员界面需要毫秒级无缝更新，并高亮变动卡片。',
    status: 'in_progress',
    priority: 'urgent',
    assigneeIds: ['usr_sarah', 'usr_alex'],
    reporterId: 'usr_michael',
    projectId: 'proj_cloud',
    startDate: '2026-08-01',
    dueDate: '2026-08-05',
    estimatedHours: 16,
    tags: ['前端', 'WebSocket', '核心功能'],
    checklist: [
      { id: 'chk_1', title: '定义广播消息 JSON Schema', completed: true },
      { id: 'chk_2', title: '前端建立心跳重连机制', completed: true },
      { id: 'chk_3', title: '卡片状态变动动画与乐观 UI 更新', completed: false },
      { id: 'chk_4', title: '多端冲突解决机制测试', completed: false },
    ],
    comments: [
      {
        id: 'cm_1',
        taskId: 'TS-101',
        authorId: 'usr_alex',
        content: '后端针对 WebSocket 断线重连已补充 Ack 确认机制，可以直接消费 `/api/ws/subscribe` 频道。',
        createdAt: '2026-08-02 10:30',
      },
      {
        id: 'cm_2',
        taskId: 'TS-101',
        authorId: 'usr_sarah',
        content: '收到！正在将前端乐观更新与组件闪烁提示融合，演示视频稍后发在 #sprint-24 频道。',
        createdAt: '2026-08-02 14:15',
      }
    ],
    activities: [
      {
        id: 'act_1',
        taskId: 'TS-101',
        authorId: 'usr_michael',
        action: '发布了新任务',
        timestamp: '2026-08-01 09:00',
      },
      {
        id: 'act_2',
        taskId: 'TS-101',
        authorId: 'usr_michael',
        action: '将优先级调整为',
        details: '紧急 (Urgent)',
        timestamp: '2026-08-01 09:05',
      },
      {
        id: 'act_3',
        taskId: 'TS-101',
        authorId: 'usr_sarah',
        action: '更新了勾选项',
        details: '完成了 "前端建立心跳重连机制"',
        timestamp: '2026-08-02 11:20',
      }
    ],
    attachmentsCount: 3,
    createdAt: '2026-08-01 09:00',
    updatedAt: '2026-08-02 14:15',
  },
  {
    id: 'TS-102',
    title: '设计新版任务详情弹窗 UI 及历史轨迹时间轴',
    description: '包含任务标题行内编辑、富文本描述、多经办人头像重叠显示、可勾选子任务清单进度条、以及全留痕的操作日志（Audit Trail）。',
    status: 'review',
    priority: 'high',
    assigneeIds: ['usr_elena'],
    reporterId: 'usr_alex',
    projectId: 'proj_cloud',
    startDate: '2026-07-29',
    dueDate: '2026-08-03',
    estimatedHours: 12,
    tags: ['UI/UX', '组件库', '设计稿'],
    checklist: [
      { id: 'chk_10', title: 'Figma 组件规范（浅色/深色适配）', completed: true },
      { id: 'chk_11', title: '交互微动画规范导出', completed: true },
      { id: 'chk_12', title: '与前端做像素级标注走查', completed: true },
    ],
    comments: [
      {
        id: 'cm_3',
        taskId: 'TS-102',
        authorId: 'usr_elena',
        content: '标注图已提交给 Sarah，增加了子任务勾选时的弹性粒子反馈。',
        createdAt: '2026-08-02 16:00',
      }
    ],
    activities: [
      {
        id: 'act_4',
        taskId: 'TS-102',
        authorId: 'usr_elena',
        action: '将状态修改为',
        details: '待代码评审 (Code Review)',
        timestamp: '2026-08-02 16:00',
      }
    ],
    attachmentsCount: 5,
    createdAt: '2026-07-29 10:00',
    updatedAt: '2026-08-02 16:00',
  },
  {
    id: 'TS-103',
    title: '构建 AI Copilot 自动拆解复杂任务与一键总结站会',
    description: '接入 Gemini API，根据用户输入的句式（例如“部署 Kubernetes 极速集群”）自动智能提取子任务清单与推荐经办人，并支持生成团队日/周报。',
    status: 'in_progress',
    priority: 'high',
    assigneeIds: ['usr_alex', 'usr_michael'],
    reporterId: 'usr_michael',
    projectId: 'proj_cloud',
    startDate: '2026-08-01',
    dueDate: '2026-08-06',
    estimatedHours: 20,
    tags: ['AI', 'Gemini', 'Backend'],
    checklist: [
      { id: 'chk_20', title: '定义 Server 端 `/api/copilot/decompose` 接口', completed: true },
      { id: 'chk_21', title: 'Prompt 提示词适配 JSON Schema 输出', completed: true },
      { id: 'chk_22', title: '前端抽屉式 AI 互动对话框', completed: false },
    ],
    comments: [
      {
        id: 'cm_4',
        taskId: 'TS-103',
        authorId: 'usr_alex',
        content: '已测试 Gemini 3.6 Flash 模型，拆解 10 个步骤仅耗时 800ms，格式非常精准！',
        createdAt: '2026-08-02 17:30',
      }
    ],
    activities: [],
    attachmentsCount: 1,
    createdAt: '2026-08-01 11:00',
    updatedAt: '2026-08-02 17:30',
  },
  {
    id: 'TS-104',
    title: '优化项目团队频道（Chat Hub）的消息 @通知 与任务联动',
    description: '支持在聊天消息中输入 `#TS-101` 自动生成交互卡片 preview，输入 `@陈亚历` 自动触发协同通知气泡与邮件提醒。',
    status: 'todo',
    priority: 'medium',
    assigneeIds: ['usr_david'],
    reporterId: 'usr_sarah',
    projectId: 'proj_cloud',
    startDate: '2026-08-04',
    dueDate: '2026-08-08',
    estimatedHours: 10,
    tags: ['聊天室', '通知', '全栈'],
    checklist: [
      { id: 'chk_30', title: '正文正则匹配卡片关联', completed: false },
      { id: 'chk_31', title: '通知红点未读消息计数引擎', completed: false },
    ],
    comments: [],
    activities: [],
    attachmentsCount: 0,
    createdAt: '2026-08-02 09:00',
    updatedAt: '2026-08-02 09:00',
  },
  {
    id: 'TS-105',
    title: '配置 DevOps CI/CD 流水线与多环境极速预发环境',
    description: '使用 Docker + Cloud Run 实现 Pull Request 自动构建独立 Preview URL，确保测试人员随时走查最新功能。',
    status: 'done',
    priority: 'medium',
    assigneeIds: ['usr_david'],
    reporterId: 'usr_alex',
    projectId: 'proj_cloud',
    startDate: '2026-07-25',
    dueDate: '2026-07-31',
    estimatedHours: 14,
    tags: ['DevOps', 'CI/CD', '基础设施'],
    checklist: [
      { id: 'chk_40', title: '编写 Dockerfile 与多阶段构建', completed: true },
      { id: 'chk_41', title: '配置 GitHub Actions / Cloud Build 自动化', completed: true },
      { id: 'chk_42', title: '验证镜像体积优化至 120MB 内', completed: true },
    ],
    comments: [
      {
        id: 'cm_5',
        taskId: 'TS-105',
        authorId: 'usr_david',
        content: 'CI/CD 已上线，每次 PR 构建时间控制在 1.5 分钟以内。',
        createdAt: '2026-07-31 18:00',
      }
    ],
    activities: [
      {
        id: 'act_5',
        taskId: 'TS-105',
        authorId: 'usr_david',
        action: '把任务状态更新为',
        details: '已完成 (Done)',
        timestamp: '2026-07-31 18:00',
      }
    ],
    attachmentsCount: 2,
    createdAt: '2026-07-25 10:00',
    updatedAt: '2026-07-31 18:00',
  },
  {
    id: 'TS-106',
    title: '发布 Sprint 24 迭代报告与客户反馈整理',
    description: '对上线后的新特性进行用户体验满意度统计，汇总 Top 3 痛点并排期 Sprint 25 Backlog。',
    status: 'backlog',
    priority: 'low',
    assigneeIds: ['usr_michael'],
    reporterId: 'usr_michael',
    projectId: 'proj_cloud',
    startDate: '2026-08-10',
    dueDate: '2026-08-12',
    estimatedHours: 6,
    tags: ['产品', '数据分析', '迭代记录'],
    checklist: [
      { id: 'chk_50', title: '收集 NPA/CSAT 问卷', completed: false },
      { id: 'chk_51', title: '召开 Team Retrospective 复盘会', completed: false },
    ],
    comments: [],
    activities: [],
    attachmentsCount: 0,
    createdAt: '2026-08-02 11:30',
    updatedAt: '2026-08-02 11:30',
  }
];

export const INITIAL_CHANNELS: ChatChannel[] = [
  {
    id: 'chan_sprint',
    projectId: 'proj_cloud',
    name: 'sprint-24-迭代沟通',
    description: 'Sprint 24 每日站会、代码评审及日常开发阻碍讨论频道',
    isPrivate: false,
    unreadCount: 2,
  },
  {
    id: 'chan_design',
    projectId: 'proj_cloud',
    name: 'design-设计交流',
    description: 'UI/UX 规范、交互原型图走查及设计反馈讨论',
    isPrivate: false,
    unreadCount: 0,
  },
  {
    id: 'chan_architecture',
    projectId: 'proj_cloud',
    name: 'architecture-技术架构',
    description: '底层数据协议、API接口规范、性能优化与安全性研讨',
    isPrivate: false,
    unreadCount: 0,
  },
  {
    id: 'chan_general',
    projectId: 'proj_cloud',
    name: 'team-大堂茶水间',
    description: '团队日常公告、灵感分享与休闲交流',
    isPrivate: false,
    unreadCount: 0,
  }
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  {
    id: 'msg_1',
    channelId: 'chan_sprint',
    authorId: 'usr_michael',
    content: '各位同学，Sprint 24 核心目标是完成实时任务看板与 AI 智能拆解助手！大家目前的进度如何？',
    createdAt: '2026-08-02 09:30',
  },
  {
    id: 'msg_2',
    channelId: 'chan_sprint',
    authorId: 'usr_sarah',
    content: '前端实时看板拖拽效果良好，目前正在对接 #TS-101 任务，已完成前端乐观更新和冲突锁定提示。',
    createdAt: '2026-08-02 09:35',
    taskRefId: 'TS-101',
  },
  {
    id: 'msg_3',
    channelId: 'chan_sprint',
    authorId: 'usr_alex',
    content: '后端针对 Gemini 3.6 Flash 的 Copilot 拆解服务已联调完成，可在 #TS-103 中点击【AI 一键拆解】体验！',
    createdAt: '2026-08-02 09:42',
    taskRefId: 'TS-103',
  },
  {
    id: 'msg_4',
    channelId: 'chan_sprint',
    authorId: 'usr_elena',
    content: '设计稿全部刷完啦！#TS-102 任务详情弹窗包含自适应时间轴，Sarah 随时可以走查。',
    createdAt: '2026-08-02 10:05',
    taskRefId: 'TS-102',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    recipientId: 'usr_sarah',
    senderId: 'usr_michael',
    type: 'assigned',
    taskId: 'TS-101',
    message: '王麦克 (Michael) 将紧急任务 "实现多人实时协作看板" 指派给了你',
    isRead: false,
    createdAt: '2026-08-01 09:01',
  },
  {
    id: 'notif_2',
    recipientId: 'usr_sarah',
    senderId: 'usr_alex',
    type: 'comment',
    taskId: 'TS-101',
    message: '陈亚历 (Alex) 在任务 TS-101 中发表了新的技术评论',
    isRead: false,
    createdAt: '2026-08-02 10:30',
  },
  {
    id: 'notif_3',
    recipientId: 'usr_sarah',
    senderId: 'usr_elena',
    type: 'mention',
    taskId: 'TS-102',
    message: '刘艾琳 (Elena) 在消息中 @了你："重构设计稿已准备就绪"',
    isRead: true,
    createdAt: '2026-08-02 16:05',
  }
];
